# Generated by Django 4.2.11 on 2025-10-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=200)),
                ('seat', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('boooking_date', models.DateTimeField(verbose_name='booking date')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField(verbose_name='release date')),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(verbose_name='seat number')),
                ('booking_status', models.CharField(choices=[('PND', 'Pending'), ('CON', 'Confirmed'), ('CAN', 'Canceled'), ('COM', 'Completed'), ('NSH', 'Now Show'), ('UNSCH', 'Unscheduled')], default='UNSCH', max_length=5, verbose_name='booking status')),
            ],
        ),
    ]
